FROM golang:1.24-bookworm AS build

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 go build -o ./build/rayls-ops-worker ./cmd/api/main.go

FROM scratch

WORKDIR /app

COPY --from=build /app/build/rayls-ops-worker /app/rayls-ops-worker
COPY --from=build /app/migrations /app/migrations
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/app/rayls-ops-worker", "worker"]
