package main

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/raylsnetwork/rayls-sovereign-ops-api/cmd/api/adapters/custody"
	"github.com/raylsnetwork/rayls-sovereign-ops-api/cmd/api/adapters/repositories"
	"github.com/raylsnetwork/rayls-sovereign-ops-api/cmd/api/auth"
	"github.com/raylsnetwork/rayls-sovereign-ops-api/cmd/api/core"
	"github.com/raylsnetwork/rayls-sovereign-ops-api/config"
	"github.com/raylsnetwork/rayls-sovereign-ops-api/domain"
	"github.com/raylsnetwork/rayls-sovereign-ops-api/infrastructure/database"
	"github.com/raylsnetwork/rayls-sovereign-ops-api/logger"
)

// seed mints short-lived JWTs for an operator and a normal user and writes them to outPath as
// ready-to-paste env vars. Missing users are auto-registered (a pure
// DB SIWE-style triplet), so the command is idempotent and needs no pre-seeding.
//
// It is a dev/CI convenience: the tokens are signed with the same JWT_SECRET the API runs with, so run
// this with the same --config as the target server. Only config, the database, repositories, and the
// token wrapper are wired — no NATS/blockchain/HSM.
func seed(configPath, operatorEmail, userEmail, outPath string, ttl time.Duration) error {
	conf, err := config.Load(configPath)
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	if conf.Custody.RaylsHSMURL == "" {
		return fmt.Errorf("seed requires HSM custody: set CUSTODY_RAYLS_HSM_URL")
	}

	logger.InitializeLogger(conf)
	log := logger.NewLogger()

	db, err := database.Connect(conf.Database.ConnectionString)
	if err != nil {
		return fmt.Errorf("failed to connect to database: %w", err)
	}

	userRepo := repositories.NewUserRepository(db)
	walletRepo := repositories.NewUserWalletRepository(db)
	providerRepo := repositories.NewUserOAuthProviderRepository(db)
	txer := database.NewTransactor(db)
	pkgz := auth.NewPkgzAuthService(conf.Auth, conf.Auth.BaseURL)
	tw := auth.NewTokenWrapper(pkgz.TokenService(), conf.Auth.JWTSecret, walletRepo, conf.Auth.AdminEmail)
	// No RPC URL: seeding only mints wallets, which is chain-agnostic — it never signs.
	custodyService := custody.NewRaylsHSM(
		conf.Custody.RaylsHSMURL,
		conf.Custody.RaylsHSMAPIKey,
		conf.Custody.RaylsHSMPassword,
		"",
	)

	ctx := context.Background()

	operator, operatorAddr, err := ensureUser(
		ctx,
		txer,
		userRepo,
		walletRepo,
		providerRepo,
		custodyService,
		log,
		"Seeded Operator",
		operatorEmail,
	)
	if err != nil {
		return fmt.Errorf("failed to ensure operator user %q: %w", operatorEmail, err)
	}
	user, userAddr, err := ensureUser(
		ctx,
		txer,
		userRepo,
		walletRepo,
		providerRepo,
		custodyService,
		log,
		"Seeded User",
		userEmail,
	)
	if err != nil {
		return fmt.Errorf("failed to ensure user %q: %w", userEmail, err)
	}

	operatorToken, err := tw.MintToken(ctx, operator, "siwe", []string{domain.RolePrivacyNodeOperator}, ttl)
	if err != nil {
		return fmt.Errorf("failed to mint operator token: %w", err)
	}
	userToken, err := tw.MintToken(ctx, user, "siwe", nil, ttl)
	if err != nil {
		return fmt.Errorf("failed to mint user token: %w", err)
	}

	content := fmt.Sprintf(
		"# Generated by `go run ./cmd/seed` (valid for %s)\n"+
			"OPS_SERVICE_OPERATOR_ADDRESS=%s\n"+
			"OPS_SERVICE_USER_ADDRESS=%s\n"+
			"OPS_SERVICE_OPERATOR_AUTH_KEY=%s\n"+
			"OPS_SERVICE_USER_AUTH_KEY=%s\n",
		ttl, operatorAddr, userAddr, operatorToken, userToken,
	)

	log.Info("Generated tokens", "out", outPath, "ttl", ttl.String(),
		"operatorEmail", operatorEmail, "operatorAddress", operatorAddr,
		"userEmail", userEmail, "userAddress", userAddr)
	fmt.Print(content)
	return nil
}

// ensureUser returns the user with the given email and their wallet address, registering a SIWE-style
// DB triplet (User + HSM-custody UserWallet + SIWE UserOAuthProvider) when it does not yet exist.
// The wallet is provisioned via the custody (Rayls HSM) service, mirroring bootstrapService.Bootstrap.
func ensureUser(
	ctx context.Context,
	txer core.Transactor,
	userRepo core.UserRepository,
	walletRepo core.UserWalletRepository,
	providerRepo core.UserOAuthProviderRepository,
	custody core.CustodyService,
	log logger.Logger,
	name, email string,
) (*domain.User, string, error) {
	existing, err := userRepo.FindByEmail(ctx, email)
	if err == nil {
		wallet, walletErr := walletRepo.FindByUserID(ctx, existing.ID)
		if walletErr != nil {
			return nil, "", fmt.Errorf("find wallet for existing user %q: %w", email, walletErr)
		}
		return existing, wallet.RaylsAddress, nil
	}
	if !errors.Is(err, core.ErrRecordNotFound) {
		return nil, "", fmt.Errorf("lookup user: %w", err)
	}

	user := &domain.User{
		Name:     name,
		Email:    email,
		IsActive: true,
		Status:   domain.UserStatusRoleAssigned,
	}

	address, externalID, err := custody.CreateWallet(ctx, user.ID)
	if err != nil {
		return nil, "", fmt.Errorf("create custody wallet: %w", err)
	}

	if err := txer.WithTransaction(ctx, func(txCtx context.Context) error {
		if err := userRepo.Create(txCtx, user); err != nil {
			return fmt.Errorf("create user: %w", err)
		}

		wallet := &domain.UserWallet{
			UserID:            user.ID,
			RaylsAddress:      address,
			CustodyProvider:   domain.CustodyProviderRaylsHSM,
			CustodyExternalID: externalID,
			Chain:             domain.WalletChainPrivate,
			IsActive:          true,
		}
		if err := walletRepo.Create(txCtx, wallet); err != nil {
			return fmt.Errorf("create user wallet: %w", err)
		}

		siweLink := &domain.UserOAuthProvider{
			UserID:        user.ID,
			OAuthID:       address,
			Provider:      domain.OAuthProviderSIWE,
			WalletAddress: address,
			Email:         email,
		}
		if err := providerRepo.Create(txCtx, siweLink); err != nil {
			return fmt.Errorf("create SIWE provider link: %w", err)
		}
		return nil
	}); err != nil {
		return nil, "", err
	}

	log.Info("Registered e2e user", "email", email, "address", address)
	return user, address, nil
}
